const topics = {
  "Array": [
    "Array",
    "Two Pointers",
    "Sliding Window",
    "Prefix Sum",
    "Matrix",
  ],
  "String": [
    "String",
    "Two Pointers",
    "Sliding Window",
    "String Matching",
    "Suffix Array",
  ],
  "Hash Table": ["Hash Table", "Hash Function", "Rolling Hash", "Counting"],
  "Binary Search": ["Binary Search", "Ternary Search"],
  "Sorting": [
    "Sorting",
    "Merge Sort",
    "Bucket Sort",
    "Counting Sort",
    "Radix Sort",
    "Quickselect",
    "Quicksort",
    "Bubble Sort",
  ],
  "Greedy": ["Greedy"],
  "Linked List": [
    "Linked List",
    "Doubly-Linked List",
    "Floyd's Cycle Finding Algorithm",
  ],
  "Stack": ["Stack", "Monotonic Stack", "Bracket Sequences"],
  "Queue": ["Queue", "Monotonic Queue"],
  "Tree": [
    "Tree",
    "Binary Tree",
    "Binary Search Tree",
    "Segment Tree",
    "Binary Indexed Tree",
    "Lowest Common Ancestor",
  ],
  "Graph Theory": [
    "Graph Theory",
    "Topological Sort",
    "Shortest Path",
    "Union-Find",
    "Strongly Connected Component",
    "Eulerian Circuit",
    "Biconnected Component",
    "Minimum Spanning Tree",
    "Directed Acyclic Graph",
    "Dijkstra's Algorithm",
    "Bipartite Graph",
    "Matching (Graph)",
    "Tarjan's SCC Algorithm",
    "A* Search",
    "Kosaraju's Algorithm",
    "Graph Coloring",
    "Kruskal's Algorithm",
    "Prim's Algorithm",
    "Hamiltonian Path",
    "Floyd–Warshall Algorithm",
    "Bellman–Ford Algorithm",
  ],
  "Depth-First Search": ["Depth-First Search"],
  "Breadth-First Search": ["Breadth-First Search"],
  "Heap (Priority Queue)": ["Heap (Priority Queue)"],
  "Trie": ["Trie"],
  "Dynamic Programming": ["Dynamic Programming", "Memoization"],
  "Recursion": ["Backtracking", "Recursion", "Divide and Conquer"],
  "Bit Manipulation": ["Bit Manipulation", "Bitmask"],
  "Math": [
    "Math",
    "Number Theory",
    "Combinatorics",
    "Geometry",
    "Probability and Statistics",
    "Game Theory",
    "Minimax",
    "Brainteaser",
    "Randomized",
    "Reservoir Sampling",
    "Rejection Sampling",
    "Meet in the Middle",
    "Greatest Common Divisor",
    "Euclidean Algorithm",
    "Prime Factorization",
    "Sieve Theory",
    "Prime Number Sieve",
    "Primality Test",
    "Fermat's Little Theorem",
    "Least Common Multiple",
    "Pigeonhole Principle",
    "Euler's Theorem",
    "Inclusion-Exclusion Principle",
    "Linear Algebra",
    "Newton's Method",
    "Nim Game",
    "Polygons",
    "Nearest Pair of Points",
    "Minimum Enclosing Circle",
  ],
  "Simulation": ["Simulation", "Enumeration"],
  "Design": ["Design", "Data Stream", "Iterator", "Ordered Set", "Concurrency"],
  "Sweep Line": ["Sweep Line"],
  "Database": ["Database"],
  "Shell": ["Shell"],
  "Interactive": ["Interactive"],
};
