const topics = {
  "Array": ["array","two-pointers","sliding-window","prefix-sum","matrix"],
  "String": ["string","two-pointers","sliding-window", "string-matching", "suffix-array"],
  "Hashing": ["hash-table", "hash-function", "rolling-hash", "counting"],
  "Binary Search": ["binary-search"],
  "Sorting": ["sorting", "merge-sort", "bucket-sort", "counting-sort", "radix-sort", "quickselect"],
  "Greedy": ["greedy"],
  "Linked List": ["linked-list", "doubly-linked-list"],
  "Stack": ["stack", "monotonic-stack"],
  "Queue": ["queue", "monotonic-queue"],
  "Tree": ["tree", "binary-tree", "binary-search-tree", "segment-tree", "binary-indexed-tree"],
  "Graph": ["graph", "topological-sort", "shortest-path", "union-find", "strongly-connected-component", "eulerian-circuit", "biconnected-component", "minimum-spanning-tree"],
  "DFS": ["depth-first-search"],
  "BFS": ["breadth-first-search"],
  "Heap": ["heap-priority-queue"],
  "Trie": ["trie"],
  "Dynamic Programming": ["dynamic-programming", "memoization"],
  "Recursion": ["backtracking", "recursion", "divide-and-conquer"],
  "Bit Manipulation": ["bit-manipulation", "bitmask"],
  "Math": ["math", "number-theory", "combinatorics", "geometry", "probability-and-statistics", "game-theory", "minimax-algorithm", "brainteaser", "randomized", "reservoir-sampling", "rejection-sampling", "meet-in-the-middle"],
  "Simulation": ["simulation", "enumeration"],
  "Design": ["design", "data-stream", "iterator", "ordered-set", "concurrency"],
  "Sweep Line": ["sweep-line"],
  "Database": ["database"],
  "Shell": ["shell"],
  "Interactive": ["interactive"]
};